import { Star, ThumbsUp, Calendar } from "lucide-react";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import MobileNav from "@/components/MobileNav";
import { navItems } from "@/nav-items";
import { Link } from "react-router-dom";

const reviews = [
  {
    id: 1,
    toolName: "ChatGPT",
    rating: 5,
    reviewer: "Sarah Johnson",
    date: "2024-01-15",
    category: "Conversational AI",
    excerpt: "ChatGPT has revolutionized how we interact with AI. The natural language understanding is incredible and it's become an essential tool for content creation and problem-solving.",
    likes: 234,
  },
  {
    id: 2,
    toolName: "Midjourney",
    rating: 5,
    reviewer: "Alex Chen",
    date: "2024-01-12",
    category: "Image Generation",
    excerpt: "The quality of images generated by Midjourney is simply outstanding. It's transformed our design workflow and helped us create stunning visuals in minutes.",
    likes: 189,
  },
  {
    id: 3,
    toolName: "Notion AI",
    rating: 4,
    reviewer: "Emily Davis",
    date: "2024-01-10",
    category: "Productivity",
    excerpt: "Notion AI seamlessly integrates with the Notion workspace. Great for summarizing notes and generating content, though it could use more advanced features.",
    likes: 156,
  },
  {
    id: 4,
    toolName: "GitHub Copilot",
    rating: 5,
    reviewer: "Michael Torres",
    date: "2024-01-08",
    category: "Code Assistant",
    excerpt: "As a developer, GitHub Copilot has become indispensable. It significantly speeds up coding and often suggests solutions I hadn't considered.",
    likes: 298,
  },
  {
    id: 5,
    toolName: "Jasper AI",
    rating: 4,
    reviewer: "Lisa Anderson",
    date: "2024-01-05",
    category: "Content Writing",
    excerpt: "Excellent for marketing copy and blog posts. The templates are useful, but sometimes requires multiple iterations to get the perfect output.",
    likes: 142,
  },
  {
    id: 6,
    toolName: "Runway ML",
    rating: 5,
    reviewer: "David Kim",
    date: "2024-01-03",
    category: "Video Editing",
    excerpt: "Runway's AI-powered video editing features are mind-blowing. The green screen removal and motion tracking work flawlessly.",
    likes: 201,
  },
];

const Reviews = () => {
  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <header className="bg-gray-900 py-4">
        <div className="container mx-auto px-4 md:px-6 lg:px-8 flex h-16 items-center justify-between">
          <div className="flex items-center gap-2">
            <Link to="/" className="text-xl sm:text-2xl font-bold text-green-400">AI Tool Tester</Link>
          </div>

          {/* Desktop Navigation */}
          <nav className="hidden lg:block">
            <ul className="flex gap-6">
              {navItems.map((item) => (
                <li key={item.to}>
                  <Link to={item.to} className="text-sm font-medium text-gray-300 hover:text-green-400 transition-colors">
                    {item.title}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>

          {/* Mobile Navigation */}
          <MobileNav navItems={navItems} />
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-12 md:py-16 lg:py-20 px-4 md:px-6 lg:px-8 bg-gradient-to-r from-gray-900 via-green-900 to-blue-900">
        <div className="container mx-auto text-center max-w-4xl">
          <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold mb-4 md:mb-6 text-white">Expert Reviews</h1>
          <p className="text-base md:text-xl text-gray-300">
            In-depth reviews from AI experts and professionals who use these tools daily
          </p>
        </div>
      </section>

      {/* Reviews Grid */}
      <section className="pb-20 px-4 md:px-6 lg:px-8 bg-gray-900">
        <div className="container mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
            {reviews.map((review) => (
              <Card key={review.id} className="flex flex-col bg-gray-800 border-gray-700 hover:bg-gray-700 transition-all">
                <CardHeader>
                  <div className="flex items-start justify-between mb-2">
                    <Badge variant="secondary" className="bg-gray-700 text-gray-300">{review.category}</Badge>
                    <div className="flex items-center gap-1">
                      {[...Array(5)].map((_, i) => (
                        <Star
                          key={i}
                          className={`h-4 w-4 ${
                            i < review.rating ? "fill-yellow-400 text-yellow-400" : "text-gray-600"
                          }`}
                        />
                      ))}
                    </div>
                  </div>
                  <CardTitle className="text-base sm:text-lg text-white">{review.toolName}</CardTitle>
                  <CardDescription className="text-sm text-gray-400">
                    by {review.reviewer}
                  </CardDescription>
                </CardHeader>
                <CardContent className="flex-1">
                  <p className="text-sm md:text-base text-gray-300 line-clamp-4">
                    {review.excerpt}
                  </p>
                </CardContent>
                <CardFooter className="flex items-center justify-between text-sm text-gray-400">
                  <div className="flex items-center gap-1">
                    <Calendar className="h-4 w-4" />
                    <span>{new Date(review.date).toLocaleDateString()}</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <ThumbsUp className="h-4 w-4" />
                    <span>{review.likes}</span>
                  </div>
                </CardFooter>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 py-8 px-4">
        <div className="container mx-auto text-center text-sm text-gray-400">
          <p>&copy; 2024 AI Tool Tester. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default Reviews;
